theme: jekyll-theme-minimal
title: Colby Snyder
logo: /assets/headshot_circle.png
description: >
  Hi, I’m Colby! I am a junior at UPenn pursuing dual Bachelor’s degrees in Chemical Engineering and Physics. I love cutting-edge research and want to help engineer a sustainable future. On the right, you’ll find some of my recent work related to these goals.

  My experience includes:
  - Nuclear materials engineering at General Atomics
  - Materials research for safer batteries in the Composto Lab
  - Computational physics at Princeton Plasma Physics Laboratory
  - Process automation engineering at Kline Process Systems

  Outside of engineering, I enjoy playing the cello, hiking, and basketball. Feel free to reach out by email or LinkedIn if you’d like to chat!

custom_css: assets/css/custom.css


