theme: jekyll-theme-minimal
title: Colby Snyder
logo: /assets/headshot_circle.png
description: Chemical engineering, physics, and materials research @ UPenn

# Add navigation links
navigation:
  - name: "Home"
    link: "/"
  - name: "Research Projects"
    link: "/research/"
  - name: "Other Projects"
    link: "/other_projects/"
