theme: jekyll-theme-minimal
title: Colby Snyder
logo: /assets/headshot_circle.png
description: >
  Hi, I’m Colby! I am a junior at UPenn pursuing dual Bachelor’s degrees in Chemical Engineering and Physics.

  Outside of engineering, I enjoy playing the cello, hiking, and basketball. Feel free to reach out by [email](mailto:colbysny@seas.upenn.edu) or [LinkedIn](https://www.linkedin.com/in/colbysny/) if you’d like to chat!

custom_css: assets/css/custom.css


